services:
  # frontend1:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   networks:
  #     - app-network
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # networks:
    #   - app-network
  nginx:
    build:
      context: "./nginx"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge
